### ISSUE TITLE
Is scaling variables recommended for fitting purposes?

### ISSUE THREAD

**Issue by patchcervan** [r-glennie/occuR#5]
I've noticed that occuR seems to fit models without much trouble even when covariates are in very different scales. Does the package scale them "under the hood"? Would it be recommended to scale/center covariates anyway? In my case, I am most interested in prediction rather than causal inference.

**Comment by r-glennie** [comment]
The package does **not** scale or centre the covariates under the hood. Typically, I leave them untransformed since, as you say typically it is ok, and this reduces work in backtransforming predictions and such. In a few cases (mostly to do with (x,y) coordinates or distance-to-coast where numbers span from small to large magnitude) I get fitting problems (no convergence or NaN variances) and in those cases I scale the covariate. So there is no catch-all rule, but if you want to super-safe without having to consider what to do for each covariate, then I'd scale and centre.

**Comment by patchcervan** [comment]
Great, thanks! That clarifies it perfectly.
